pipeline {
    agent any

    environment {
        SRC_DIR = "${PWD}/projects"
        BACKUP_DIR = "${PWD}/backups"
    }

    stages {
        stage('Backup Directory') {
            steps {
                script {
                    sh '''
                        ts=$(date +"%Y-%m-%d-%H-%M-%S")
                        mkdir -p "$BACKUP_DIR"
                        tar -czvf "$BACKUP_DIR/backup_$ts.tar.gz" -C "$SRC_DIR" .
                        echo "✅ Compressed backup created: $BACKUP_DIR/backup_$ts.tar.gz"
                    '''
                }
            }
        }
    }
}
